# Generated by Django 4.1.7 on 2023-03-14 16:00

import auto_prefetch
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='description')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='price')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('beds', models.PositiveSmallIntegerField(default=0, verbose_name='beds')),
                ('bedroom', models.PositiveSmallIntegerField(default=0, verbose_name='bedrooms')),
                ('guests', models.PositiveSmallIntegerField(default=0, verbose_name='guests')),
                ('check_in', models.TimeField(verbose_name='check_in')),
                ('check_out', models.TimeField(verbose_name='checkout')),
                ('instant_book', models.BooleanField(default=False, verbose_name='instant book')),
                ('host', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
