# Generated by Django 4.1.7 on 2023-03-14 16:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
    ]
