# Generated by Django 4.1.7 on 2023-03-14 16:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='baths',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='baths'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
    ]
