# Generated by Django 4.1.7 on 2023-03-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_roomtype_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='subtitle',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
