# Generated by Django 4.1.7 on 2023-03-15 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_roomphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomphoto',
            options={'verbose_name': 'Room Photo'},
        ),
    ]
