# Generated by Django 4.1.7 on 2023-03-16 07:57

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_alter_room_amenities_alter_room_facilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomphoto',
            name='room',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomphotos', to='rooms.room', verbose_name='room'),
        ),
    ]
