# Generated by Django 4.1.7 on 2023-03-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_alter_roomphoto_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=100, verbose_name='caption'),
        ),
    ]
