# Generated by Django 4.1.7 on 2023-03-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='check_in',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Check In'),
        ),
    ]
