# Generated by Django 4.1.7 on 2023-03-14 12:08

import airbnb.utils.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=airbnb.utils.media.MediaHelper.avatar_upload_path, verbose_name='Avatar'),
        ),
    ]
