# Generated by Django 4.1.7 on 2023-03-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='langauge',
            field=models.CharField(choices=[('en', 'English'), ('kr', 'Korean')], default='en', max_length=2),
        ),
    ]
