# Generated by Django 4.1.7 on 2023-03-14 13:12

import airbnb.utils.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customuser_birthdate_customuser_langauge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('krw', 'KRW')], default='usd', max_length=3, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='superhost',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=airbnb.utils.media.MediaHelper.avatar_upload_path, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other, Other', 'Other')], default='male', max_length=20, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='langauge',
            field=models.CharField(choices=[('en', 'English'), ('kr', 'Korean')], default='en', max_length=2, verbose_name='langauge'),
        ),
    ]
