name: Test and Release Django Project

on:
  push:
    branches: [ "development" ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: "Run code analysis"
        run: |
          git ls-files | grep -v 'migrations' | grep -v 'settings.py' | grep -v 'manage.py' | grep -E '.py$' | xargs pylint -E --load-plugins=pylint_django
      - name: "Run tests"
        run: |
          python manage.py test
      # - name: "Run security checks"
      #   run: |
      #     python manage.py check --deploy --fail-level ERROR
